from __future__ import annotations

import asyncio
import json
import multiprocessing
import os
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest
from sqlalchemy import create_engine, text

from api_server import sources, store
from api_server.db import PublicFeedRow
from api_server.feed_coordination import (
    MAX_SNAPSHOT_BYTES,
    PUBLIC_FEED_KEYS,
    PublicFeedCoordinator,
)


def _engine(path: str):
    return create_engine(
        f"sqlite:///{path}",
        connect_args={"check_same_thread": False, "timeout": 10},
    )


def _event(provider: str, when: datetime | None = None) -> dict:
    when = when or datetime.now(timezone.utc) - timedelta(minutes=5)
    timestamp = when.isoformat().replace("+00:00", "Z")
    return {
        "id": provider,
        "title": f"{provider} report",
        "question": "What changed?",
        "url": f"https://news.example/{provider.lower().replace(' ', '-')}",
        "provider": provider,
        "publishedAt": timestamp,
        "retrievedAt": timestamp,
        "freshness": "CURRENT",
    }


def _spawn_cache_worker(database_path, start, calls, results):
    """Run a genuinely independent cache and connection pool."""
    from api_server import sources as child_sources
    from api_server.feed_coordination import PublicFeedCoordinator as ChildCoordinator

    async def fake_fetch(client, provider, url):
        calls.put(provider)
        # Keep the lease holder alive long enough for the peer to observe it.
        await asyncio.sleep(0.12)
        event = _event(provider)
        return [event], {
            "provider": provider,
            "status": "OK",
            "message": "Provider check succeeded.",
        }

    child_sources._fetch_current_provider = fake_fetch
    database = _engine(database_path)
    cache = child_sources.CurrentEventDiscoveryCache(
        ChildCoordinator(database, lease_seconds=1),
    )
    start.wait(10)
    try:
        results.put(("ok", asyncio.run(cache.get())))
    except BaseException as exc:
        results.put(("error", repr(exc)))
    finally:
        database.dispose()


def _spawn_abandoned_holder(database_path, marker_path, key, lease_seconds):
    """Acquire a lease, prove acquisition durably, then die without cleanup."""
    coordinator = PublicFeedCoordinator(
        _engine(database_path), lease_seconds=lease_seconds,
    )
    token, _, _, _ = coordinator.claim_or_read(key)
    Path(marker_path).write_text(token or "", encoding="utf-8")
    os._exit(23)


@pytest.fixture
def sqlite_feeds(tmp_path):
    path = str(tmp_path / "public-feeds.sqlite")
    schema_engine = _engine(path)
    PublicFeedRow.__table__.create(schema_engine)
    schema_engine.dispose()
    engines = [_engine(path), _engine(path)]
    try:
        yield path, engines
    finally:
        for database in engines:
            database.dispose()


def test_spawned_caches_coalesce_fixed_providers_and_preserve_winner_timestamps(sqlite_feeds):
    path, _ = sqlite_feeds
    context = multiprocessing.get_context("spawn")
    start = context.Event()
    calls = context.Queue()
    results = context.Queue()
    workers = [
        context.Process(
            target=_spawn_cache_worker,
            args=(path, start, calls, results),
        )
        for _ in range(2)
    ]
    for worker in workers:
        worker.start()
    start.set()
    for worker in workers:
        worker.join(15)
        assert worker.exitcode == 0

    responses = [results.get(timeout=2) for _ in workers]
    assert [kind for kind, _ in responses] == ["ok", "ok"]
    feeds = [payload for _, payload in responses]
    observed_calls = [calls.get(timeout=2) for _ in PUBLIC_FEED_KEYS]
    assert sorted(observed_calls) == sorted(provider for provider, _ in sources.CURRENT_EVENT_PROVIDERS)
    # Both processes restore exactly what the lease winner published. In
    # particular, retrieval/check timestamps are not regenerated by readers.
    assert feeds[0]["events"] == feeds[1]["events"]
    assert feeds[0]["checkedAt"] == feeds[1]["checkedAt"]
    assert [
        (status["checkedAt"], status["lastAttemptAt"])
        for status in feeds[0]["providers"]
    ] == [
        (status["checkedAt"], status["lastAttemptAt"])
        for status in feeds[1]["providers"]
    ]
    assert [event["retrievedAt"] for event in feeds[0]["events"]]
    assert all(
        status["checkedAt"] == status["lastAttemptAt"]
        for status in feeds[0]["providers"]
    )


@pytest.mark.asyncio
async def test_shared_sql_cache_preserves_cooldowns_fallback_age_empty_and_freshness(
    sqlite_feeds, monkeypatch,
):
    _, engines = sqlite_feeds
    states = {provider: "ok" for provider, _ in sources.CURRENT_EVENT_PROVIDERS}
    calls: list[str] = []
    original_dates: dict[str, str] = {}

    async def fake_fetch(client, provider, url):
        calls.append(provider)
        state = states[provider]
        if state == "error":
            return [], {
                "provider": provider,
                "status": "ERROR",
                "message": "Provider request timed out.",
            }
        events = [] if state == "empty" else [_event(provider)]
        if events:
            original_dates[provider] = events[0]["publishedAt"]
        return events, {
            "provider": provider,
            "status": "OK",
            "message": "Provider check succeeded.",
        }

    monkeypatch.setattr(sources, "_fetch_current_provider", fake_fetch)
    first_cache = sources.CurrentEventDiscoveryCache(PublicFeedCoordinator(engines[0], 1))
    first = await first_cache.get()
    assert len(first["events"]) == 2
    assert len(calls) == 2

    # A separate cache and engine honor the persisted success TTL.
    second_cache = sources.CurrentEventDiscoveryCache(PublicFeedCoordinator(engines[1], 1))
    hit = await second_cache.get()
    assert len(calls) == 2
    assert hit["events"] == first["events"]
    assert hit["checkedAt"] == first["checkedAt"]
    assert all(item["cached"] and not item["stale"] for item in hit["providers"])

    # Expire only BBC, then preserve its good snapshot across a failed attempt.
    states["BBC News"] = "error"
    with engines[0].begin() as connection:
        connection.execute(text(
            "UPDATE public_feed_coordination SET retry_at = 0 "
            "WHERE provider_key = 'bbc-world-v1'"
        ))
    failed = await sources.CurrentEventDiscoveryCache(
        PublicFeedCoordinator(engines[1], 1),
    ).get()
    assert calls.count("BBC News") == 2
    bbc_status = next(item for item in failed["providers"] if item["provider"] == "BBC News")
    assert bbc_status["status"] == "ERROR"
    assert bbc_status["cached"] and bbc_status["stale"]
    assert bbc_status["checkedAt"] == first["providers"][1]["checkedAt"]
    assert bbc_status["lastAttemptAt"] != bbc_status["checkedAt"]
    assert next(event for event in failed["events"] if event["provider"] == "BBC News")[
        "publishedAt"
    ] == original_dates["BBC News"]

    # Error cooldown is shared too: another engine must not call the backend.
    during_cooldown = await sources.CurrentEventDiscoveryCache(
        PublicFeedCoordinator(engines[0], 1),
    ).get()
    assert calls.count("BBC News") == 2
    assert next(item for item in during_cooldown["providers"] if item["provider"] == "BBC News")[
        "lastAttemptAt"
    ] == bbc_status["lastAttemptAt"]

    # Successful empty is authoritative and replaces the prior good data.
    states["BBC News"] = "empty"
    with engines[0].begin() as connection:
        connection.execute(text(
            "UPDATE public_feed_coordination SET retry_at = 0 "
            "WHERE provider_key = 'bbc-world-v1'"
        ))
    empty = await sources.CurrentEventDiscoveryCache(
        PublicFeedCoordinator(engines[1], 1),
    ).get()
    assert not any(event["provider"] == "BBC News" for event in empty["events"])
    assert next(item for item in empty["providers"] if item["provider"] == "BBC News")[
        "status"
    ] == "OK"

    # An old successful snapshot is not eligible as stale fallback.
    states["BBC News"] = "error"
    with engines[0].begin() as connection:
        good = json.loads(connection.execute(text(
            "SELECT good FROM public_feed_coordination "
            "WHERE provider_key = 'bbc-world-v1'"
        )).scalar_one())
        good["stored_at"] -= sources.CURRENT_EVENT_STALE_SECONDS + 1
        connection.execute(text(
            "UPDATE public_feed_coordination SET good = :good, retry_at = 0 "
            "WHERE provider_key = 'bbc-world-v1'"
        ), {"good": json.dumps(good)})
    expired = await sources.CurrentEventDiscoveryCache(
        PublicFeedCoordinator(engines[0], 1),
    ).get()
    expired_bbc = next(item for item in expired["providers"] if item["provider"] == "BBC News")
    assert expired_bbc["status"] == "ERROR" and not expired_bbc["stale"]
    assert not any(event["provider"] == "BBC News" for event in expired["events"])

    # Publication freshness is rechecked when a persisted snapshot is read,
    # without rewriting its authentic provider timestamp.
    with engines[0].begin() as connection:
        google = json.loads(connection.execute(text(
            "SELECT latest FROM public_feed_coordination "
            "WHERE provider_key = 'google-world-v1'"
        )).scalar_one())
        old_date = (
            datetime.now(timezone.utc)
            - timedelta(hours=sources.CURRENT_EVENT_FRESHNESS_HOURS, seconds=2)
        ).isoformat().replace("+00:00", "Z")
        google["events"][0]["publishedAt"] = old_date
        connection.execute(text(
            "UPDATE public_feed_coordination SET latest = :snapshot, good = :snapshot "
            "WHERE provider_key = 'google-world-v1'"
        ), {"snapshot": json.dumps(google)})
    filtered = await sources.CurrentEventDiscoveryCache(
        PublicFeedCoordinator(engines[1], 1),
    ).get()
    assert filtered["events"] == []
    with engines[0].connect() as connection:
        persisted = json.loads(connection.execute(text(
            "SELECT latest FROM public_feed_coordination "
            "WHERE provider_key = 'google-world-v1'"
        )).scalar_one())
    assert persisted["events"][0]["publishedAt"] == old_date


def test_expired_killed_holder_recovers_and_old_token_is_fenced(sqlite_feeds, tmp_path):
    path, engines = sqlite_feeds
    lease_seconds = 0.25
    marker = tmp_path / "claimed"
    context = multiprocessing.get_context("spawn")
    holder = context.Process(
        target=_spawn_abandoned_holder,
        args=(path, str(marker), PUBLIC_FEED_KEYS[0], lease_seconds),
    )
    holder.start()
    holder.join(10)
    assert holder.exitcode == 23
    old_token = marker.read_text(encoding="utf-8")
    assert old_token

    replacement = PublicFeedCoordinator(engines[0], lease_seconds=lease_seconds)
    token, latest, good, _ = replacement.claim_or_read(PUBLIC_FEED_KEYS[0])
    assert token is None and latest is None and good is None
    time.sleep(lease_seconds + 0.12)
    new_token, _, _, _ = replacement.claim_or_read(PUBLIC_FEED_KEYS[0])
    assert new_token and new_token != old_token

    snapshot = {
        "events": [_event("Google News")],
        "status": {"provider": "Google News", "status": "OK", "message": "ok"},
        "checked_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
    }
    assert not PublicFeedCoordinator(engines[1], lease_seconds).publish(
        PUBLIC_FEED_KEYS[0], old_token, snapshot, 60,
    )
    assert replacement.publish(PUBLIC_FEED_KEYS[0], new_token, snapshot, 60)


def test_coordinator_rejects_unknown_keys_and_bounded_snapshots(sqlite_feeds):
    _, engines = sqlite_feeds
    coordinator = PublicFeedCoordinator(engines[0], lease_seconds=2)
    with pytest.raises(ValueError, match="fixed public feed"):
        coordinator.claim_or_read("attacker-controlled")
    with pytest.raises(ValueError, match="fixed public feed"):
        coordinator.publish("attacker-controlled", "token", {}, 1)

    token, _, _, _ = coordinator.claim_or_read(PUBLIC_FEED_KEYS[0])
    oversized_count = {
        "events": [{} for _ in range(13)],
        "status": {"status": "OK"},
        "checked_at": "2026-01-01T00:00:00Z",
    }
    with pytest.raises(ValueError, match="Too many"):
        coordinator.publish(PUBLIC_FEED_KEYS[0], token, oversized_count, 60)

    oversized_bytes = {
        "events": [],
        "status": {"status": "OK", "message": "x" * MAX_SNAPSHOT_BYTES},
        "checked_at": "2026-01-01T00:00:00Z",
    }
    with pytest.raises(ValueError, match="size limit"):
        coordinator.publish(PUBLIC_FEED_KEYS[0], token, oversized_bytes, 60)


@pytest.mark.asyncio
async def test_classification_gate_precedes_discovery_backend(monkeypatch):
    async def forbidden():
        raise AssertionError("restricted request reached discovery backend")

    monkeypatch.setattr(store, "discover_current_events", forbidden)
    for classification in ("CUI", "SECRET", "TS", "unknown", None):
        response = await store.list_current_events(classification)
        assert response["blocked"] and response["events"] == []